config/routes.rb
Rails.application.routes.draw do
  resources :tweets
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "tweets#index"

end

app/models/announcement.rb
class Announcement < ApplicationRecord
  has_many :comments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

    belongs_to :announcement
    belongs_to :commentable, polymorphic: true


end

#
# Comment id: nil, content: nil, announcement_id: nil, commentable_id: nil,>
#
# Comment.new(content:"TEST comment", announcement_id: Announcement )
#
# <Comment id: 1, content: "Studentcomment!!!", announcement_id: 1, commentable_id: 1, commentable_type: "Student", created_at: "2021-03-10 21:14:43", updated_at: "2021-03-10 21:14:43">,
#
# <Comment id: 2, content: "teacher comment joo!", announcement_id: 1, commentable_id: 1, commentable_type: "Teacher", created_at: "2021-03-10 21:16:02", updated_at: "2021-03-10 21:16:02">]> 

app/models/student.rb
class Student < ApplicationRecord
  has_many :comments, as: :commentable
end


Student.last.comments.create!(content:"Studentcomment!!!", announcement_id:Announcement.new)


# ActiveRecord::Relation [#<Announcement id: 1, created_at: "2021-03-10 21:02:17", updated_at: "2021-03-10 21:02:17", content: "First Announcement">, #<Announcement id: 2, created_at: "2021-03-10 21:03:05", updated_at: "2021-03-10 21:03:05", content: "First Announcement">, #<Announcement id: 3, created_at: "2021-03-10 21:14:28", updated_at: "2021-03-10 21:14:28", content: "mijn annoounc">]> 

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_many :comments, as: :commentable
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  after_create_commit { broadcast_prepend_to "tweets" }
  after_update_commit { broadcast_replace_to "tweets" }
  after_destroy_commit { broadcast_remove_to "tweets" }

  validates :title, :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ]

  # GET /tweets or /tweets.json
  def index
    @tweets = Tweet.all
    @tweet = Tweet.new
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweets_url, notice: "Tweet was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.turbo_stream {render turbo_stream: turbo_stream.replace(@tweet, partial: "tweets/form", locals: {tweet: @tweet}) }
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tweeter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= yield :head %>
    <%= turbo_include_tags %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, id: dom_id(tweet)) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<%= turbo_frame_tag dom_id(tweet) do %>
  <div class="card card-body">
    <div><%= tweet.title %></div>



      <%= link_to "Edit", edit_tweet_path(tweet) %>
    </div>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= turbo_frame_tag dom_id(@tweet) do %>
  <div class="card card-body">
    <%= render 'form', tweet: @tweet %>
    <%= link_to "Cancel", @tweet %>
  </div>
<% end %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tweeter</h1>

<%= turbo_stream_from "tweets" %>

<%= turbo_frame_tag "tweet_form" do %>
  <%= render "tweets/form", tweet: @tweet %>
<% end %>

<%= turbo_frame_tag "tweets" do %>
  <%= render @tweets %>
<% end %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<%= turbo_frame_tag dom_id(@tweet) do %>
  <%= render @tweet %>
<% end %>


<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>